---
title: "2019-05-15"
output: html_document
---



#7-5 

names(): 從vector角度對元素進行名稱查詢
names() <-：可用來命名

```{r}
Vector1 <- letters[1:6]
Vector1
names(Vector1)
```
```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```
```{r}
Vector1[["名稱1"]]
```
```{r}
Mat1
names(Mat1) 
names(Mat1) <- letters[1:6]
names(Mat1)
```

##colnames()/rownames()

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```
```{r}
colnames(StuDF2)
names(StuDF2)
```
更改名稱
```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
```
只改col2
```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
```
改col2和col3
```{r}
colnames(StuDF2)[c(2,3)] <- c("col-2","col-3")
colnames(StuDF2)
```
```{r}
colnames(StuDF2) <- c("StudentID","Name","Grade")
colnames(StuDF2)
```
```{r}
rownames(StuDF2) <- str_c("第", 1:5 ,"筆")
rownames(StuDF2)
```

#7.6.1 使用[[.]] <-或$. <-

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在 # 視為新增
a
```
將下面的TRUE換成FALSE, 並增加第5個元素其值為數字7。
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素3 <- "FALSE"
b[[5]] <- "7"
b
```
```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```














































