---
title: "2019-06-05"
output: html_document
---

#function usage

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
utility_cobb_douglass(y=2,1,0.5,0.8)
```

#iteration
執行以下程序得到transcriptDataFinal資料及平均成績計算函數gpa_fun():
```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號

studentIds5 <- studentIds[1:5]# 以前5筆學號為sequence_source
studentIds5
```

作法一:
```{r}
for (i in studentIds5) {
  print(i)
}
```
作法二:
```{r}
for (i in c(1:5)) {
  print(i)
  print(studentIds5[[i]])
}
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```
一
```{r}
for (g in gmailAddress) {
  print(g)
}
```
二
```{r}
for (g in c(1:4)) {
  print(g)
  print(gmailAddress[[g]])
}
```
三
```{r}
for (g in seq_along(gmailAddress)) {
  print(gmailAddress[[g]])
}
```





























































