---
title: "2019-05-15"
output: html_document
---

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF$姓名)

StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
```{r}

```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素3 <- FALSE
b[[5]] <- 7
b
```


```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
library(lubridate)
date <- ymd(exData3$期間)
class(date)
```
```{r}
isAsiaCrisis <- ( date >="1997-06-01" & date<="1998-12-01")
isAsiaCrisis
```

[.R,.C]




















