---
title: "2019-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
引入套件
```{r}
library(stringr)
library(lubridate)
```
no pakage
```{r}
install.packages("stringr")
```
#str_subset()查詢其中元素是否含有此條件
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
```
#偵測（detect）元素裡是否符合某種規律
```{r}
str_detect(course,"經濟學")
```
#利用str_sub()取出以下每位學生系別及入學年
```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
str_sub(studentID,5,6) #學系號
str_sub(studentID,2,4) #學年
```

#JOIN
>合併多個向量

```{r}
month<-c("3","4","2")
day<-c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```
 別的寫法
 1.
```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```
 2.(sep表seperate,即分隔用"-")
```{r}
month
day
str_c(month,day, sep="-")
```

#SPLIT切割
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

#REPLACE取代

```{r}
dates
str_replace(dates,"-","月")
```
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
"https://github.com"
username[1:2]
reponame[1:2]
str_c("https://github.com",username[1:2],reponame[1:2],sep="/")
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```
```{r}
Sys.getlocale()
Sys.setlocale(category = "LC_ALL", locale = "UTF-8")
```
#將birthday變成“西元yyyy年mm月dd日”型式
```{r}
year<-str_sub(birthday,1,4)
month<-str_sub(birthday,5,6)
day<-str_sub(birthday,7,8)
head(str_c("西元",year,"年",month,"月",day,"日"))
```


#將下述資料轉成西元年月格式的date class
```{r}
time1<-c("099/01","099/02","099/03")
class(time1)
```

 1.將"099/01"化成"099""01"
```{r}
year1<-str_sub(time1,1,3)
month1<-str_sub(time1,5,6)
```
 2."099"變成99
 3.99+1911
```{r}
year2<-as.integer(year1)+1911
```
 4.合併
```{r}
str_c("西元",year2,"年",month1,"月")
```
















