---
title: "2019-05-29"
output: html_document
---


>browseURL()函數可以輸入網址後自動開啟瀏覽器連到該網頁

```{r}
textbookURL<-function(){
browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#section-8.1")}
textbookURL()
```

>若有多個物件值要輸出，可以先併成一個list物件輸出。

```{r}

library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")


gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```
```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```


## 創造一個demand_supply_fun(P,a,b,c,d)，它會輸出一個list包含三個元素：供給量，需求量，超額供給量

```{r}
demand_supply_fun <- function(P,a,b,c,d){
  supply <- a + (b*P)
  demand <- c - (d*P)
  gap <- supply - demand
  return(
    list(
      供給量 = supply,
      需求量 = demand,
      超額供給量 = gap
    )
  )
}
```

# 依條件執行
>if(邏輯條件){
  成立時執行
}

ex.
```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```
```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1)
supply_fun3(P=2,0,1)
```
>print()是單純的訊息輸出，而message()是用在「錯誤」狀況下的訊息顯示。兩者在程式除錯時，會有明顯差別。


## 修改範例2的gpa_fun, 若輸入學號不存在則在螢幕顯示“查無此學號”。
```{r}

gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
      transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
  }else{
    message("查無此學號")
  }
}



gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
 fizzbuzz<-function(d){

  if(d%%3==0 & d%%5==0)
    {print("fizzbuzz")}
  else if(d%%3==0)
     {print("fizz")}
  else if(d%%5==0)
     {print("buzz")}
  else{print(d)}
 }
```


```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```
```{r}
a>2
any(a>2)
all(a>2)
```

```{r}
a <- 3

testfun <- function(x){
  y <- a/4
  output <- x*y
  return(output)
}

testfun(2)

a <- 4
testfun(2)
```








































