---
title: "2019-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#矩陣- Matrix

```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
```
```{r}
class(Mat1)
typeof(Mat1)
```
```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
class(Mat2)
typeof(Mat2)
```

>list：因為三個變數向量的type不相同，只能用list儲存。

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
>data frame：若每個變數相同元素位置來自於同一筆資料，我們可以使用data frame的class來儲存這樣的（長）方形資料表。

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```
```{r}
class(StuDF)
typeof(StuDF)
```
>取出胖虎

```{r}
StuDF[[2]][[3]]
```

```{r}
class(StuDF$姓名)

StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```
```{r}
class(StuDF)
typeof(StuDF)
```
```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) #轉成小寫
toupper(m) #轉成大寫
```
```{r}
chosenLETTERS[8]
matObj1[8]
```
```{r}
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```
```{r}
matObj1[c(TRUE,F,F,TRUE,F),c(F,TRUE,TRUE)]
```
#課堂練習
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
class(classSurvey)
```
取出性別及學分數
```{r}
classSurvey[,4:5]
```
```{r}
classSurvey[c(1:60),c(4:5)]
```




























